url: "https://blackbox.github.io"  # the base URL for your site
baseurl: "https://blackboxgeo.github.io"  # leave this blank unless you're hosting the site in a subdirectory

# GitHub Pages settings
github:
  is_project_page: true